
CREATE TABLE IF NOT EXISTS roles (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS  categories (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS options (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
price DECIMAL(10,2) NOT NULL,
image VARCHAR(300) NULL
);

CREATE TABLE IF NOT EXISTS orders (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
ticket_number VARCHAR(100) NOT NULL,
order_date DATETIME NOT NULL,
total_price DECIMAL(10,2) NOT NULL,
status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS menus (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
description TEXT NULL,
price  DECIMAL(10,2) NOT NULL, 
image VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
role_id INT UNSIGNED NOT NULL,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL, -- hash de password_hash()
FOREIGN KEY(role_id)REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS products (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
category_id INT UNSIGNED NOT NULL,
FOREIGN KEY(category_id)REFERENCES categories(id),
name VARCHAR(255) NOT NULL,
description TEXT NULL,
price DECIMAL(10,2) NOT NULL,
image VARCHAR(255) NOT NULL
);


CREATE TABLE product_options(
    product_id INT UNSIGNED NOT NULL,
    option_id INT UNSIGNED NOT NULL,
    PRIMARY KEY(product_id, option_id),
    FOREIGN KEY(product_id ) REFERENCES products(id),
    FOREIGN KEY(option_id ) REFERENCES options(id)
)


CREATE TABLE menu_product(
    menu_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL,
    quantity TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY(product_id, menu_id),
    FOREIGN KEY(product_id ) REFERENCES products(id),
    FOREIGN KEY(menu_id ) REFERENCES menus(id)
)


CREATE TABLE IF NOT EXISTS order_items (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
orders_id INT UNSIGNEDNOT NULL,
products_id INT UNSIGNED NOT NULL,
name VARCHAR(255) NOT NULL,
quantity TINYINT UNSIGNED NOT NULL,
price DECIMAL(10,2) NOT NULL,
FOREIGN KEY(orders_id)REFERENCES orders(id),
FOREIGN KEY(products_id)REFERENCES products(id)
);

